import Header from "../components/head/Header";
import ScrollBerCategori from "../components/category/ScrollBerCategori";
import apiData from "../public/apiData.json"

import SearchResult from "../components/head/SearchResult";
import Footer from "../components/Footer";
import Head from "next/head";
import { useState } from "react";

function Categories({data}) {
  
///from child call back
const [quantity, setQuantity]= useState(1)
const [showINC,setShowINC] = useState(false);
const toogle = () => {
    setShowINC(false);
 }
 const qtytoogle = () => {
 setQuantity(1);
 }

    return (
        <div className=" relative  ">
           <Head>
           <title  > {data.title.title} </title>
            <meta name="description" content="Generated by Hs-developer" />
        {data.settings?.map(({id,icon})=>(
         <link key={id} rel="icon" href={icon[0]} />
      ))}
      </Head>
           <Header  posts={data.products}
             settings={data.settings} 
             button={data.headerPart2}
             siteButton={data.siteBerButton} />
          
           <div  className=" mt-10 max-h-full max-w-screen-2xl mx-auto ">
          
             
             
              <ScrollBerCategori 
              data={data}
              settings={data.settings}
              posts={data.products} />

           
          
            </div>
            <SearchResult  posts={data.products} toogle={toogle}   qtytoogle={qtytoogle}  />
            <footer >
            <Footer settings={data.settings} />
            </footer>
           
        </div>
    )
}

export default Categories


export async function getStaticProps(context) {
  
   const data = apiData
 
   return {
     props: { data }, 
   }
 }