import Head from 'next/head'
import { useEffect, useState } from 'react'
import apiData from "../public/apiData.json"
import Header from "../components/head/Header"
import SearchResult from "../components/head/SearchResult"
import Banner from "../components/body/Banner"
import Categories from "../components/category/Categories";
import HomeBody from "../components/body/HomeBody";
import Footer from '../components/Footer'

    export default function Home({data,posts,categori,topranked,PersonalEquipment,mostView,
      GlobalCollection,Dropshipping,settings,herobanner}) {


///from child call back
const [quantity, setQuantity]= useState(1)
const [showINC,setShowINC] = useState(false);
const toogle = () => {
    setShowINC(false);
 }
 const qtytoogle = () => {
 setQuantity(1);
 }
 

 console.log(data.heroBanner)
  return (
    <div className="relative" >
     <Head>
     <title  > {data.title.title} </title>
      <meta name="description" content="Generated by Hs-developer" />
        {data.settings?.map(({id,icon})=>(
         <link key={id} rel="icon" href={icon[0]} />
      ))}
      </Head>
      <Header 
         posts={data.products}
        settings={data.settings} 
        button={data.headerPart2}
        siteButton={data.siteBerButton}
        />
           
      <main className="max-h-full max-w-screen-2xl mx-auto" >
      <SearchResult  posts={data.products} toogle={toogle}   qtytoogle={qtytoogle} />
        <div>
        {data.heroBanner?.map(({id,image}) =>(
       <Banner key={id} image01={image[0]} 
       image02={image[1]} 
       image03={image[2]} 
       />))}
       
       <Categories categori={data.categoryshow.arrival}
        Dropshipping={data.categoryshow.Dropshipping}
        topranked={data.categoryshow.Topranked}
        PersonalEquipment={data.categoryshow.Personal}
        mostView={data.categoryshow.TrueView}
        GlobalCollection={data.categoryshow.Global}
        settings={data.settings}
        />
      <HomeBody posts={data.products}
       settings={data.settings}
       bannerPart2={data.bannerPart2}
       bannerPart3={data.bannerPart3}
       bannerPart4={data.bannerPart4}
        />
        </div>
      
      </main>

      <footer >
      <Footer settings={data.settings} />
      </footer>
     
    </div>
  )
};


export async function getStaticProps(context) {
  
  const data = apiData

  return {
    props: { data }, 
  }
}