import apiData from "../public/apiData.json"
import Head from "next/head"
import Footer from "../components/Footer";
import Header from "../components/head/Header"
import OrderItems from "../components/order/OrderItems";
import SearchResult from "../components/head/SearchResult";

import { useState } from "react";
import { useSelector } from "react-redux";
import { selectOrder } from "../reduxStore/productReduc";

function Oderlist({data}) {
 
  ///from child call back
const [quantity, setQuantity]= useState(1)
const [showINC,setShowINC] = useState(false);
const toogle = () => {
    setShowINC(false);
 }
 const qtytoogle = () => {
 setQuantity(1);
 }

 
    return (
        <div>
             <Head>
             <title  > {data.title.title} </title>
              <meta name="description" content="Generated by Hs-developer" />
        {data.settings?.map(({id,icon})=>(
         <link key={id} rel="icon" href={icon[0]} />
      ))}
      </Head>
            <Header posts={data.products}
        settings={data.settings} 
        button={data.headerPart2}
        siteButton={data.siteBerButton}  />
            <main className="lg:flex max-w-screen-2xl mx-auto">
       {/*From api order data keep this OderItems components and post there replace orderBusket 
       example:  <OrderItems posts={apifromData}   settings={data.settings}  /> */}
            <OrderItems    settings={data.settings}  />
            </main>
            <SearchResult posts={data.products} toogle={toogle}   qtytoogle={qtytoogle}   />
            <Footer settings={data.settings} />
        </div>
    )
}

export default Oderlist



export async function getStaticProps(context) {
  
  const data = apiData

  return {
    props: { data }, 
  }
}